{
 "title": "Vesuv3000",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperatur",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vesuv Status Actual",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "# LED\n\n{{Led1}}\n\n{{Led2}}\n\n# ErrorStatus {{ErrorState}}\n\n# Schalter {{Schalter}}\n\n# Temperatur {{temp}}"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(Led1) as Led1,last(Led2) as Led2,last(ErrorStatus) as ErrorState,last(Schalter) as Schalter,last(value) as temp  FROM temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vesuv Status TimeRange",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": {
    "content": "# LED\n\n{{Led1}}\n\n{{Led2}}\n\n# ErrorStatus {{ErrorState}}\n\n# Schalter {{Schalter}}\n\n# Temperatur {{temp}}"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(Led1) as Led1,last(Led2) as Led2,last(ErrorStatus) as ErrorState,last(Schalter) as Schalter,last(value) as temp  FROM temperature WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pumpstufe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "Pumpstufe" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FIRE",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "Fire" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Schalter",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT \"Schalter\" FROM \"temperature\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}